### ISSUE TITLE
Add a way to set BASE_URL for frontend

### ISSUE THREAD

**Issue by serbaut** [coreroller/coreroller#58]
This would make it possible to run the coreroller web and api under e.g. /test/coreroller/ instead of /.

**Comment by tegioz** [comment]
Hi @serbaut 

Could you explain a bit more the use case for this?

**Comment by serbaut** [comment]
We mount coreroller under /something/coreroller/ using url rewrites. We do the same for /something/kibana/ and /something/grafana/. Grafana is a pain since it has to recompile the frontend if the path changes which takes minutes but i can see that you have a BASE_URL variable that works fine, I just need to be able to set it somehow.

**Comment by serbaut** [comment]
This is how our kubernetes ingress for coreroller looks:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollerd
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /comething/coreroller/
        backend:
          serviceName: rollerd
          servicePort: 80
```
and the resulting nginx config:

        rewrite /something/coreroller/(.*) /$1 break;
        proxy_pass http://default-rollerd-80;

This works with  `BASE_URL=/something/coreroller/api` in API.js.
